{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "invulnerable.fullname" . }}-backend
  labels:
    {{- include "invulnerable.backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "invulnerable.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "invulnerable.backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "invulnerable.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: backend
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: {{ include "invulnerable.backend.image" . | quote }}
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.backend.service.targetPort }}
          protocol: TCP
        env:
        - name: PORT
          value: {{ .Values.backend.service.targetPort | quote }}
        - name: DB_HOST
          value: {{ .Values.backend.database.host | quote }}
        - name: DB_PORT
          value: {{ .Values.backend.database.port | quote }}
        - name: DB_USER
          value: {{ .Values.backend.database.user | quote }}
        - name: DB_PASSWORD
          {{- if .Values.backend.database.existingSecret }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend.database.existingSecret }}
              key: {{ .Values.backend.database.passwordKey }}
          {{- else }}
          value: {{ .Values.backend.database.password | quote }}
          {{- end }}
        - name: DB_NAME
          value: {{ .Values.backend.database.name | quote }}
        - name: DB_SSLMODE
          value: {{ .Values.backend.database.sslmode | quote }}
        livenessProbe:
          {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
