{{- if and .Values.oauth2Proxy.enabled (not .Values.oauth2Proxy.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "invulnerable.fullname" . }}-oauth2-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "invulnerable.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
type: Opaque
data:
  client-id: {{ .Values.oauth2Proxy.clientID | b64enc | quote }}
  client-secret: {{ .Values.oauth2Proxy.clientSecret | b64enc | quote }}
  cookie-secret: {{ .Values.oauth2Proxy.cookieSecret | b64enc | quote }}
{{- end }}
